### ISSUE TITLE
HazelcastSessionManager.findSession can return null for an existing session under load

### ISSUE THREAD

**Issue by gokhanoner** [hazelcast/hazelcast-tomcat-sessionmanager#42]
I believe the issue is in this method: https://github.com/hazelcast/hazelcast-tomcat-sessionmanager/blob/master/tomcat8/src/main/java/com/hazelcast/session/HazelcastSessionManager.java#L226

from `findSession` method

```
HazelcastSession hazelcastSession = sessionMap.get(id);
if (hazelcastSession == null) {
  log.info("No Session found for:" + id);
  return null;
}
.....
// call remove method to trigger eviction Listener on each node to invalidate local sessions
sessionMap.remove(id);
sessionMap.set(id, hazelcastSession);
```

After checking `sessionMap`, if the session is present, first remove & then set called. After `remove` & before `set` call, if you call the same method, you can get `null` from `sessionMap.get(id)` call. This could cause users getting null for an existing session under load, as described in https://github.com/hazelcast/hazelcast-tomcat-sessionmanager/pull/41

**Comment by gokhanoner** [comment]
@edwardsmatt As you pointed out, the main with issue replacing `remove` and `set` with `sessionMap.put` is that there's an EntryListener & it counts on eviction event. I'll also check what can be done. Your solution for EntryListener seems promising. I'll update the ticket soon.

**Comment by edwardsmatt** [comment]
Hi @gokhanoner, 
I've implemented a test version using the map `entryAdded` and `entryUpdated` `EntryListener` events as discussed, however what I have seen is that when a session contains an object that is not on the tomcat classpath (i.e. a custom object on the application classpath), we end up with a ClassNotFoundException when trying to deserialize the object contained within the `EntryEvent`. I can put together an example if that's what is required.

However, I can also verify that PR #41 fixes this issue as well.

Have you had any chance to investigate a fix, if so are you able to provide an update to see if we can progress a fix?

Thanks very much 👍

**Comment by alparslanavci** [comment]
@edwardsmatt thank you for providing a detailed reproduce case. It helped a lot. I send a PR for the fix of this issue, and tested it with your case. Please see #61.

**Comment by ghkarmseveer** [comment]
Hi,

I've just tried using this fix (by compiling master locally) but it does not seem to fix it - I still get sessions not being found under high load.

I think the fix does not lock enough, the sessionMap.get needs to be in a lock too:

```
            HazelcastSession hazelcastSession;
            sessionMap.lock(id);
            try {
                hazelcastSession = sessionMap.get(id);
            } finally {
                sessionMap.unlock(id);
            }

```

with that in place I can simulate a high load and get no lost sessions

**Comment by alparslanavci** [comment]
@ghkarmseveer can you please provide a reproducer for your case? It would be really helpful for us to fix if any issues remain.

**Comment by ghkarmseveer** [comment]
Hi,

I've shamelessly forked @edwardsmatt exampleansd updated it to tomcat 8.5 . locally I get failures with the 1.1.4 release

https://github.com/ghkarmseveer/hazelcast-tomcat-sessionmanager-42-example


No I'm not using sticky sessions

**Comment by alparslanavci** [comment]
@ghkarmseveer, in your example, you are trying to download `hazelcast-tomcat85-sessionmanager-1.1.4.jar` from secure Github releases page using `curl` command. It will not allow to download from a secure page directly without adding certificates. Can you please try to download from maven repo instead? See the example below:

```
curl http://central.maven.org/maven2/com/hazelcast/hazelcast-tomcat85-sessionmanager/1.1.4/hazelcast-tomcat85-sessionmanager-1.1.4.jar > cluster/lib/hazelcast-tomcat85-sessionmanager-1.1.4.jar
```

I run your test with using 1.1.4 and don't face any issues. Please let us know if you are still getting the failures.

**Comment by ghkarmseveer** [comment]
@alparslanavci sorry about the download link but still fails for me locally:

![image](https://user-images.githubusercontent.com/25149612/68296457-92690900-008c-11ea-86e1-4baf8c41885a.png)
